# Generated by Django 5.2.6 on 2025-09-26 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaRegistros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitante',
            old_name='fecha',
            new_name='fecha_visita',
        ),
        migrations.RenameField(
            model_name='visitante',
            old_name='hora',
            new_name='hora_visita',
        ),
    ]
