# Generated by Django 5.2.6 on 2025-09-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaRegistros', '0003_rename_hora_visita_visitante_hora_entrada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('motivo_visita', models.TextField(max_length=500)),
                ('fecha_visita', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Visitante',
        ),
    ]
