# Generated by Django 5.2.6 on 2025-09-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaRegistros', '0004_visita_delete_visitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='motivo_visita',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='visita',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
