# Generated by Django 5.2.6 on 2025-09-26 17:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SistemaRegistros", "0002_rename_fecha_visitante_fecha_visita_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="visitante",
            old_name="hora_visita",
            new_name="hora_entrada",
        ),
        migrations.AddField(
            model_name="visitante",
            name="hora_salida",
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
