# Generated by Django 5.2.6 on 2025-10-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaRegistros', '0005_alter_visita_motivo_visita_alter_visita_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='rut',
            field=models.CharField(max_length=10),
        ),
    ]
